		const TabErreur = [];
		TabErreur[0] = "pas d'erreur";
		TabErreur[6] = "Le cendrier est plein";
		TabErreur[7] = "la grille ne s'ouvre pas";
		TabErreur[27] = "Température de fumées trop basse";
		TabErreur[29] = "Defaut de combustion, démarrage impossible";
		TabErreur[32] = "Temps de Remplissage dépassé"	
		TabErreur[70] = "niveau silo bas"
		TabErreur[93] = "cendrier ouvert"
		TabErreur[229] = "Nettoyer/Contrôler le détecteur de niveau de granulés"
		TabErreur[371] = "Vérifier l'encrassement du foyer, nettoyer si nécessaire"
		TabErreur[7101] = "Temps Maxi de charge du Ballon dépassé. Contrôler les heures, la sonde, la pompe"
